name: Publish multi-version Docker image to Docker Hub

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hrocha/python
      TAG_SUFFIX: -alpine-gcc
      PYTHON_VERSIONS: "3.13"  # <--- adicione versões aqui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push for all versions
        run: |
          for PYTHON_VERSION in $PYTHON_VERSIONS; do
            echo ">>> Building Python ${PYTHON_VERSION}"
            docker buildx build \
              --build-arg PYTHON_VERSION=${PYTHON_VERSION} \
              --platform linux/amd64,linux/arm64 \
              --push \
              -t $IMAGE_NAME:${PYTHON_VERSION}${TAG_SUFFIX} \
              .
          done
